num_objects_range:
- 4
- 4
target:
- blue
COLORS:
- blue
- green
- yellow
- red
mode: easy
rew_type: sparse
state_size: 40
render_mode: image
tags: cwtargetN4C4S1S1,easymode,sparserewtype
num_stacked_obss: 1
obs_size: 64
obs_channels: 3
task: target
name: CwTargetN4C4S1S1Env
env: CwTargetEnv
